services:
  fision-web:
    container_name: fision-web
    image: "riowilliam08/fision-web:latest"
    ports:
      - "4200:80"
    build:
      context: .
      args:
        NGINX: nginx.conf
    volumes:
      - .:/app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "14"
